This is a valid query, but the program produces an exception instead.
